---
title: "lab07_assignment"
author: "Author Asbjørn Hansen (s215045), Emiliano Carrara (s250828), Magnus Eriksen (s215066), Oliver Sonne Buch (s215079) & Trine Brøgger (s211443)"
format:
  html:
    embed-resources: true
editor: visual
---

# PCA tidyverse style

## Loading Libraries

```{r}
#| echo: true
#| eval: true
#| message: false

library("tidyverse")
library("broom")
library("cowplot")
```

## Load Data

The data is downloaded from wilkelab

```{r}
#| echo: true
#| eval: true
#| message: false

biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Creating PCA fit variable

```{r}
print(biopsy)
```

```{r}
pca_fit <- biopsy |> 
  select(-outcome) |> 
  prcomp(scale = TRUE)
```

## Look at the data in PC coordinates 1

Using pca_fit results and combining them with outcome from biopsy.

```{r}
pca_fit
```

Object becomes a tibble when using augment:

```{r}
pca_fit %>%
  augment(biopsy)
```

```{r}
pca_fit |> 
  augment(biopsy) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```

## Look at the data in PC coordinates 2

## Look at the variance explained by each PC

```{r}
#| echo: true
#| eval: true

pca_fit |>
  tidy(matrix = "eigenvalues")
```

```{r}
#| echo: true
#| eval: true

pca_fit |> 
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```
